---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(here)
theme_set(theme_minimal())
```


```{r}
dados = read_csv(here("data/threewise-distances_deepchromaOTI_sl10.csv"),
                 col_types = "cccddddddddddddl") %>%
                 select(
                     mfcc_similar = simple_mfcc_c1,
                     mfcc_dissimilar = simple_mfcc_c2,
                     mfcc_sd = simple_mfcc_c3,
                     mfcc_ds = simple_mfcc_c4,
                     mfcc_dissimilar_inv = simple_mfcc_c5,
                     mfcc_similar_inv = simple_mfcc_c6,
                     chroma_similar = simple_chroma_c1,
                     chroma_dissimilar = simple_chroma_c2,
                     chroma_sd = simple_chroma_c3,
                     chroma_ds = simple_chroma_c4,
                     chroma_dissimilar_inv = simple_chroma_c5,
                     chroma_similar_inv = simple_chroma_c6, 
                     `sim(A,B) > sim(A,C)` = `y = sim(A,B) > sim(A,C) ^ sim(B,A) > sim(B,C)`
                 )
                 
balanceados = read_csv(here("data/balanced_threewise-distances_deepchromaOTI_sl10.csv"),
                       col_types = "ddddddddddl")

dados = dados %>% 
    mutate(ABmAC_chroma = chroma_similar - chroma_dissimilar,
           ABmAC_mfcc = mfcc_similar - mfcc_dissimilar)

summary(dados)
```

```{r}
box_e_pontos = function(p){
    p + 
    geom_boxplot(outlier.colour = NA, width = .2) + 
    geom_jitter(width = .15, alpha = .3, size = .5) + 
    theme(legend.position = "None")
}

```


```{r}
dados %>% 
    gather(key = "comparação", value = "subtração", 
           chroma_similar, chroma_dissimilar) %>% 
    ggplot(aes(x = `subtração`, colour = `comparação`)) + 
    geom_histogram(bins = 30, fill = "white") + 
    geom_rug(alpha = .2) + 
    facet_grid(`comparação` ~ ., scales = "free")

dados %>% 
    gather(key = "comparação", value = "subtração", 
           mfcc_similar, mfcc_dissimilar) %>% 
    ggplot(aes(x = `subtração`, colour = `comparação`)) + 
    geom_histogram(bins = 30, fill = "white") + 
    geom_rug(alpha = .2) + 
    facet_grid(`comparação` ~ ., scales = "free")

```



```{r}
balanceados %>% 
    ggplot(aes(x = ab_gt_ac, 
               y = ab_mfcc - ac_mfcc, 
               color = ab_gt_ac))  %>%
    box_e_pontos()
```


```{r}
balanceados %>% 
    ggplot(aes(x = ab_gt_ac, 
               y = ab_chroma - ac_chroma, 
               color = ab_gt_ac))  %>%
    box_e_pontos()

balanceados %>% 
    ggplot(aes(x = ab_gt_ac, 
               y = ab_chroma_simetric1 - ac_chroma_simetric1, 
               color = ab_gt_ac))  %>%
    box_e_pontos()


balanceados %>% 
    ggplot(aes(x = ab_gt_ac, 
               y = ab_chroma_simetric1 - ac_chroma_simetric2, 
               color = ab_gt_ac))  %>%
    box_e_pontos()


```


```{r}
dados %>% 
    ggplot(aes(x = mfcc_similar, y = mfcc_dissimilar)) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0)
```


```{r}
balanceados %>% 
    ggplot(aes(x = ab_chroma - ac_chroma, 
               y = ab_mfcc - ac_mfcc,
               color = ab_gt_ac)) + 
    geom_point(size = .8, alpha = .8) 

```

```{r}
balanceados %>% 
    ggplot(aes(x = ab_chroma - ac_chroma, 
               y = ab_mfcc - ac_mfcc,
               fill = ab_gt_ac)) +  
    # geom_point(size = 3, alpha = .3)
    geom_hex(alpha = .5)
```


```{r}
balanceados %>% 
    ggplot(aes(x = ab_chroma - ac_chroma, 
               y = ab_mfcc - ac_mfcc,
               color = ab_gt_ac)) +  
    geom_density2d()
```


```{r}
library(broom)

tofit = balanceados %>%  
    mutate(chroma = ab_chroma - ac_chroma, 
           mfcc = ab_mfcc - ac_mfcc)
m = glm(ab_gt_ac ~ chroma + mfcc, family = "binomial", tofit)

tidy(m, exponentiate = T)

w_predictions = augment(m, 
                        type.predict = "response") 

w_predictions = w_predictions %>% 
  mutate(predicted = ifelse(.fitted > .5, "1", "0"))

table(w_predictions$predicted, w_predictions$ab_gt_ac)

w_predictions %>% 
    summarise(acc = sum((predicted == 1) == ab_gt_ac) / n())
```



```{r}
triplasl = dados %>%
    arrange(-mfcc_AB) %>%
    mutate(t = 1:n()) %>%
    gather(
    key = "comparação",
    value = "valor",
    mfcc_similar,
    mfcc_dissimilar,
    mfcc_BC,
    chroma_AB,
    chroma_AC,
    chroma_BC
    )
# 
# triplasl %>% 
#     group_by(`comparação`) %>% 
#     summarise(media = mean(`valor`), 
#               mediana = median(valor), 
#               min = min(valor), 
#               max = max(valor))

# triplasl %>% 
#     # filter(t <= 10) %>% 
#     ggplot(aes(x = t,  y = `valor`, colour = `comparação`)) + 
#     geom_point(alpha = 1, size = 1)

```

